{{- $name := include "quai-docs.name" . -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ $name }}
  name: {{ $name }}
  namespace: {{ .Values.quaiDocs.env }}
spec:
  progressDeadlineSeconds: 600
  replicas: {{ .Values.quaiDocs.replicas }}
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: {{ $name }}
  template:
    metadata:
      labels:
        app: {{ $name }}
    spec:
      containers:
      - image: {{ .Values.quaiDocs.image.name -}}:{{- .Values.quaiDocs.image.version }}
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 1
          httpGet:
            path: /
            port: http
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: {{ $name }}
        ports:
        - containerPort: 3000
          name: http
          protocol: TCP
        resources: {}
        startupProbe:
          failureThreshold: 30
          httpGet:
            path: /
            port: http
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
