{{- if .Values.quaiDocs.cloud }}
{{- $name := include "quai-docs.name" . -}}
apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: {{ $name }}
spec:
  redirectToHttps:
    enabled: true
{{- end }}