{{- $name := include "quai-docs.name" . -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}
  namespace: {{ .Values.quaiDocs.env }}
spec:
  ports:
  - name: http
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: {{ $name }}
  type: NodePort
